name: Build iOS 1.0.0 (29) (paused)

# Trigger disabled after Build 29 started to prevent duplicate builds.

jobs:
  build_ios:
    name: Build iOS 1.0.0 (29)
    type: build
    params:
      platform: ios
      profile: production
