name: Submit iOS build 30

on:
  push:
    branches: ['feature/v1.3.4-location-widget-ui']

jobs:
  submit_ios:
    name: Upload build 30 to App Store Connect
    type: submit
    params:
      build_id: 561f3e54-beec-46c1-a131-1a305c3dfb16
      profile: production
